org: jamesdrape
app: serverless-standup
service: standup-reminder
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  cronHandler:
    handler: index.run
    events:
      - schedule: cron(30 9 ? * MON-FRI *)
